package com.moltenbits.gasp.jooq;

import org.jooq.codegen.GeneratorStrategy.Mode;
import org.jooq.codegen.JavaGenerator;
import org.jooq.codegen.JavaWriter;
import org.jooq.meta.ColumnDefinition;
import org.jooq.meta.ForeignKeyDefinition;
import org.jooq.meta.InverseForeignKeyDefinition;
import org.jooq.meta.ManyToManyKeyDefinition;
import org.jooq.meta.SchemaDefinition;
import org.jooq.meta.TableDefinition;
import org.jooq.meta.UniqueKeyDefinition;

import java.io.File;
import java.util.List;

/**
 * Custom jOOQ code generator that produces standalone GraphQL schema descriptor
 * classes alongside the standard jOOQ Table classes.
 * <p>
 * The generated Table classes are left completely clean — no GASP annotations,
 * no extra methods. Instead, a separate {@code XxxGraphQLSchema} class is generated
 * for each non-join table into a {@code .schema} sub-package.
 * <p>
 * These descriptors carry GASP annotations for columns and relationships, and exist
 * purely for the annotation processor to scan at compile time.
 * <p>
 * Users can customize the GraphQL schema by extending the descriptor:
 * <pre>
 * &#64;GraphQLType(name = "Book", explicitFieldsOnly = true)
 * public class BookSchema extends BookGraphQLSchema {
 *     &#64;GraphQLIgnore &#64;Override public Long prequelId() { return null; }
 * }
 * </pre>
 */
public class GaspJooqGenerator extends JavaGenerator {

    private static final String GASP_PKG = "com.moltenbits.gasp.annotation";
    private static final String SCHEMA_SUFFIX = "GraphQLSchema";

    @Override
    protected void generateTable(SchemaDefinition schema, TableDefinition table) {
        super.generateTable(schema, table);

        if (!isJoinTable(table)) {
            generateSchemaDescriptor(table);
        }
    }

    private String schemaPkg() {
        return getStrategy().getTargetPackage() + ".schema";
    }

    private String schemaClassName(TableDefinition table) {
        return getStrategy().getJavaClassName(table) + SCHEMA_SUFFIX;
    }

    private void generateSchemaDescriptor(TableDefinition table) {
        String targetPkg = schemaPkg();
        String className = schemaClassName(table);

        File dir = new File(getStrategy().getTargetDirectory(), targetPkg.replace('.', '/'));
        dir.mkdirs();

        File file = new File(dir, className + ".java");

        // Use jOOQ's JavaWriter so the file is tracked and not cleaned up
        JavaWriter out = newJavaWriter(file);

        out.println("package %s;", targetPkg);
        out.println();

        out.javadoc("GraphQL schema descriptor for the %s table.\nGenerated by GaspJooqGenerator — compile-time only.", table.getName());
        out.println("@%s.GraphQLType(explicitFieldsOnly = true)", GASP_PKG);
        out.println("public class %s {", className);

        // Column accessors — use fully-qualified types to avoid import issues
        for (ColumnDefinition col : table.getColumns()) {
            String fieldName = toCamelCase(col.getName());
            String javaType = resolveColumnType(col);

            out.println();

            if (isPrimaryKey(col)) {
                out.println("@%s.GraphQLId", GASP_PKG);
            }
            if (!col.getType().isNullable() && !isPrimaryKey(col)) {
                out.println("@%s.GraphQLNonNull", GASP_PKG);
            }
            out.println("@%s.GraphQLField", GASP_PKG);
            out.println("public %s %s() { return null; }", javaType, fieldName);
        }

        // Relationships: one-to-many (inverse FKs)
        for (InverseForeignKeyDefinition ifk : table.getInverseForeignKeys()) {
            TableDefinition referencingTable = ifk.getReferencingTable();
            if (isJoinTable(referencingTable)) continue;
            if (referencingTable.equals(table)) continue;

            String targetClass = schemaPkg() + "." + schemaClassName(referencingTable);
            String fieldName = toCamelCase(referencingTable.getName()) + "s";

            out.println();
            out.println("@%s.GraphQLRelation(entity = %s.class, list = true)", GASP_PKG, targetClass);
            out.println("public Object %s() { return null; }", fieldName);
        }

        // Relationships: many-to-many
        for (ManyToManyKeyDefinition m2m : table.getManyToManyKeys()) {
            ForeignKeyDefinition fk1 = m2m.getForeignKey1();
            ForeignKeyDefinition fk2 = m2m.getForeignKey2();
            TableDefinition targetTable = fk1.getReferencedTable().equals(table)
                    ? fk2.getReferencedTable()
                    : fk1.getReferencedTable();

            String targetClass = schemaPkg() + "." + schemaClassName(targetTable);
            String fieldName = toCamelCase(targetTable.getName()) + "s";

            out.println();
            out.println("@%s.GraphQLRelation(entity = %s.class, list = true)", GASP_PKG, targetClass);
            out.println("public Object %s() { return null; }", fieldName);
        }

        // Relationships: many-to-one (outgoing FKs)
        for (ForeignKeyDefinition fk : table.getForeignKeys()) {
            TableDefinition referencedTable = fk.getReferencedTable();
            String targetClass = schemaPkg() + "." + schemaClassName(referencedTable);
            String fieldName = referencedTable.equals(table)
                    ? deriveFieldNameFromFK(fk, table)
                    : toCamelCase(referencedTable.getName());

            out.println();
            out.println("@%s.GraphQLRelation(entity = %s.class)", GASP_PKG, targetClass);
            out.println("public Object %s() { return null; }", fieldName);
        }

        out.println("}");

        closeJavaWriter(out);
    }

    private String resolveColumnType(ColumnDefinition col) {
        String dbType = col.getType().getType().toUpperCase();
        if (dbType.contains("BIGINT")) return "Long";
        if (dbType.contains("INT")) return "Integer";
        if (dbType.contains("VARCHAR") || dbType.contains("CHAR") || dbType.contains("TEXT") || dbType.contains("CLOB")) return "String";
        if (dbType.contains("BOOLEAN") || dbType.contains("BIT")) return "Boolean";
        if (dbType.contains("TIMESTAMP") || dbType.contains("DATETIME")) return "java.time.LocalDateTime";
        if (dbType.contains("DATE")) return "java.time.LocalDate";
        if (dbType.contains("DECIMAL") || dbType.contains("NUMERIC")) return "java.math.BigDecimal";
        if (dbType.contains("FLOAT") || dbType.contains("DOUBLE") || dbType.contains("REAL")) return "Double";
        return "String";
    }

    private boolean isPrimaryKey(ColumnDefinition column) {
        TableDefinition table = column.getContainer();
        UniqueKeyDefinition pk = table.getPrimaryKey();
        if (pk == null) return false;
        return pk.getKeyColumns().stream()
                .anyMatch(c -> c.getName().equals(column.getName()));
    }

    private boolean isJoinTable(TableDefinition table) {
        UniqueKeyDefinition pk = table.getPrimaryKey();
        if (pk == null || pk.getKeyColumns().size() < 2) return false;

        List<String> fkColumnNames = table.getForeignKeys().stream()
                .flatMap(fk -> fk.getKeyColumns().stream())
                .map(ColumnDefinition::getName)
                .toList();

        return table.getColumns().stream()
                .allMatch(col -> fkColumnNames.contains(col.getName()));
    }

    private static String toCamelCase(String snakeCase) {
        StringBuilder sb = new StringBuilder();
        boolean capitalizeNext = false;
        for (char c : snakeCase.toLowerCase().toCharArray()) {
            if (c == '_') {
                capitalizeNext = true;
            } else {
                sb.append(capitalizeNext ? Character.toUpperCase(c) : c);
                capitalizeNext = false;
            }
        }
        return sb.toString();
    }

    private String deriveFieldNameFromFK(ForeignKeyDefinition fk, TableDefinition ownerTable) {
        String fkName = fk.getName().toUpperCase();
        String tableName = ownerTable.getName().toUpperCase();

        if (fkName.startsWith("FK_")) fkName = fkName.substring(3);
        if (fkName.startsWith(tableName + "_")) fkName = fkName.substring(tableName.length() + 1);

        return toCamelCase(fkName);
    }
}
